version: "3"

services:
  board-game-front:
    image: board-game-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
      - "3001:443"
    restart: always
    networks:
      - boardnetwork

networks:
  boardnetwork:
    driver: bridge